In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv("./0-1400.csv")
df1.drop('Unnamed: 0', axis=1, inplace=True)

df2=pd.read_csv("./1400_2800.csv")
df2.drop('Unnamed: 0', axis=1, inplace=True)

df3=pd.read_csv("./2800-4159.csv")

df4=pd.read_csv("./전세_아파트_리스트.csv", encoding='cp949')

df5=pd.read_csv("./차집합데이터.csv")
df5.drop('Unnamed: 0', axis=1, inplace=True)

In [3]:
df_total=pd.concat([df1,df2,df3,df5])
df_total=df_total[df_total['new_zibun']!='None']
df_total.reset_index(inplace=True, drop=True)

In [4]:
df_drop = df_total.drop_duplicates(['apt', 'new_road','home_cnt','home_size','room_cnt', 'bath_cnt'])
df_drop=df_drop[['apt', 'road', 'new_apt', 'new_road', 'latitude', 'longitude',
       'company', 'home_cnt', 'home_size', 'room_cnt', 'bath_cnt', 'bigo',
       'zibun', 'new_zibun']]
df_drop

,apt,road,new_apt,new_road,latitude,longitude,company,home_cnt,home_size,room_cnt,bath_cnt,bigo,zibun,new_zibun
0,개포동 개포2차현대아파트(220),언주로 103,개포현대2차(220동),개포동,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,강남구 개포동 655-2,강남구 개포동 655-2
1,개포동 개포6차우성아파트1동~8동,언주로 3,우성6차,언주로 3,37.476763,127.057210,우성건설(주),270,54.98,2,1,None,강남구 개포동 658-1,강남구 개포동 658-1
2,개포동 개포6차우성아파트1동~8동,언주로 3,우성6차,언주로 3,37.476763,127.057210,우성건설(주),270,67.28,3,1,None,강남구 개포동 658-1,강남구 개포동 658-1
3,개포동 개포6차우성아파트1동~8동,언주로 3,우성6차,언주로 3,37.476763,127.057210,우성건설(주),270,79.97,3,1,None,강남구 개포동 658-1,강남구 개포동 658-1
4,개포동 개포자이(12-2),개포로109길 69,개포자이,개포로109길 69,37.496437,127.077115,LG건설(주),212,134.30,4,2,None,강남구 개포동 12-2,강남구 개포동 12-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24216,북한산삼부르네상스(21.7.15),포방터8길 30,북한산삼부르네상스,포방터8길 30,37.600887,126.949987,-,305,84.51,3,2,None,서대문구 8-205,서대문구 홍은동 8-1212
24218,북한산삼부르네상스(21.7.15),포방터8길 30,북한산삼부르네상스,포방터8길 30,37.600887,126.949987,-,305,98.47,3,2,None,서대문구 8-205,서대문구 홍은동 8-1212
24219,골드넷멤버스빌리지,서래로2길 29,골드넛멤버스빌리지,서래로2길 29,37.496116,126.999970,(주)미사건설,5,69.96,3,2,None,서초구 78-11,서초구 반포동 78-11
24220,골드넷멤버스빌리지,서래로2길 29,골드넛멤버스빌리지,서래로2길 29,37.496116,126.999970,(주)미사건설,5,128.66,4,2,None,서초구 78-11,서초구 반포동 78-11
24221,골드넷멤버스빌리지,서래로2길 29,골드넛멤버스빌리지,서래로2길 29,37.496116,126.999970,(주)미사건설,5,156.93,4,2,None,서초구 78-11,서초구 반포동 78-11

In [5]:
df4

,apt,road,new_apt,new_road,latitude,longitude,company,home_cnt,home_size,room_cnt,bath_cnt,bigo,zibun,new_zibun
0,개포동 개포2차현대아파트(220),언주로 103,개포현대2차(220동),개포동,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,None,None
1,개포동 개포6차우성아파트1동~8동,언주로 3,정든우성6단지,불정로 195,37.361885,127.122656,수도배관(공용배관) 교체완료(2014년),706,84.97,3,2,None,None,None
2,개포동 개포우성3차,개포로 307,우성3차,개포로 307,37.483998,127.056011,우성건설(주),405,104.43,3,1,None,None,None
3,개포동 개포우성3차,개포로 307,우성3차,개포로 307,37.483998,127.056011,우성건설(주),405,133.46,4,2,None,None,None
4,개포동 개포우성3차,개포로 307,우성3차,개포로 307,37.483998,127.056011,우성건설(주),405,161.00,5,2,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31043,장안동 에스아이팰리스장안센텀,한천로2길 84,에스아이팰리스장안센텀(주상복합),한천로2길 84,37.562386,127.063230,(주)성우에스아이,99,28.75,2,1,None,None,None
31044,장안동 에스아이팰리스장안센텀,한천로2길 84,에스아이팰리스장안센텀(주상복합),한천로2길 84,37.562386,127.063230,(주)성우에스아이,99,47.20,3,1,None,None,None
31045,장안동 청명에버아트2차,장한로21길 19-15,청명에버아트2차(주상복합),장한로21길 19-15,37.569645,127.068760,주식회사지성건설,18,37.07,1,1,None,None,None
31046,장안동 청명에버아트2차,장한로21길 19-15,청명에버아트2차(주상복합),장한로21길 19-15,37.569645,127.068760,주식회사지성건설,18,48.72,2,1,None,None,None
31047,휘경동 캠퍼스드림오피스텔,이문로 10,캠퍼스드림,이문로 10,37.588768,127.054688,에스원건설(주),52,21.29,1,1,None,None,None

In [6]:
df_result=pd.concat([df4, df_drop])
df_result = df_result.drop_duplicates(['apt', 'new_road', 'home_cnt', 'home_size', 'room_cnt', 'bath_cnt'])
df_result=df_result[df_result['latitude']!=0]
df_result=df_result[df_result['bath_cnt']!='-']
df_result.reset_index(drop=True, inplace=True)
df_result

,apt,road,new_apt,new_road,latitude,longitude,company,home_cnt,home_size,room_cnt,bath_cnt,bigo,zibun,new_zibun
0,개포동 개포2차현대아파트(220),언주로 103,개포현대2차(220동),개포동,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,None,None
1,개포동 개포6차우성아파트1동~8동,언주로 3,정든우성6단지,불정로 195,37.361885,127.122656,수도배관(공용배관) 교체완료(2014년),706,84.97,3,2,None,None,None
2,개포동 개포우성3차,개포로 307,우성3차,개포로 307,37.483998,127.056011,우성건설(주),405,104.43,3,1,None,None,None
3,개포동 개포우성3차,개포로 307,우성3차,개포로 307,37.483998,127.056011,우성건설(주),405,133.46,4,2,None,None,None
4,개포동 개포우성3차,개포로 307,우성3차,개포로 307,37.483998,127.056011,우성건설(주),405,161.00,5,2,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37392,북한산삼부르네상스(21.7.15),포방터8길 30,북한산삼부르네상스,포방터8길 30,37.600887,126.949987,-,305,84.51,3,2,None,서대문구 8-205,서대문구 홍은동 8-1212
37393,북한산삼부르네상스(21.7.15),포방터8길 30,북한산삼부르네상스,포방터8길 30,37.600887,126.949987,-,305,98.47,3,2,None,서대문구 8-205,서대문구 홍은동 8-1212
37394,골드넷멤버스빌리지,서래로2길 29,골드넛멤버스빌리지,서래로2길 29,37.496116,126.999970,(주)미사건설,5,69.96,3,2,None,서초구 78-11,서초구 반포동 78-11
37395,골드넷멤버스빌리지,서래로2길 29,골드넛멤버스빌리지,서래로2길 29,37.496116,126.999970,(주)미사건설,5,128.66,4,2,None,서초구 78-11,서초구 반포동 78-11
37396,골드넷멤버스빌리지,서래로2길 29,골드넛멤버스빌리지,서래로2길 29,37.496116,126.999970,(주)미사건설,5,156.93,4,2,None,서초구 78-11,서초구 반포동 78-11

In [7]:
df_result.to_csv('./전세_아파트_리스트_완성본.csv', index=False, encoding='cp949')

In [8]:
df=pd.read_csv("./전세_전처리_데이터.csv")
df

,주소,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),층,건축년도,도로명,동_단지,시군구,번지
0,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201501,13,"40,000",5,1988.0,언주로 103,개포동 개포2차현대아파트(220),서울특별시 강남구 개포동,655-2
1,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201503,2,"50,000",2,1988.0,언주로 103,개포동 개포2차현대아파트(220),서울특별시 강남구 개포동,655-2
2,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201505,23,"50,000",6,1988.0,언주로 103,개포동 개포2차현대아파트(220),서울특별시 강남구 개포동,655-2
3,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201506,8,"49,000",3,1988.0,언주로 103,개포동 개포2차현대아파트(220),서울특별시 강남구 개포동,655-2
4,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201507,22,"50,000",9,1988.0,언주로 103,개포동 개포2차현대아파트(220),서울특별시 강남구 개포동,655-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
823273,서울특별시 중랑구 중화동 450,한신아파트(103~109),전세,50.37,202204,2,"37,000",21,1997.0,동일로 752,중화동 한신아파트(103~109),서울특별시 중랑구 중화동,450
823274,서울특별시 중랑구 중화동 450,한신아파트(103~109),전세,50.37,202204,2,"37,000",21,1997.0,동일로 752,중화동 한신아파트(103~109),서울특별시 중랑구 중화동,450
823275,서울특별시 중랑구 중화동 450,한신아파트(103~109),전세,59.76,202204,16,"46,000",4,1997.0,동일로 752,중화동 한신아파트(103~109),서울특별시 중랑구 중화동,450
823276,서울특별시 중랑구 중화동 450,한신아파트(103~109),전세,84.69,202204,27,"51,000",7,1997.0,동일로 752,중화동 한신아파트(103~109),서울특별시 중랑구 중화동,450
823277,서울특별시 중랑구 중화동 450,한신아파트(103~109),전세,59.76,202204,30,"33,600",23,1997.0,동일로 752,중화동 한신아파트(103~109),서울특별시 중랑구 중화동,450

In [11]:
df_final=pd.merge(df, df_result, left_on=['동_단지', '전용면적(㎡)'], right_on=['apt', 'home_size'], how='inner')
df_final = df_final.drop_duplicates(['주소','전용면적(㎡)','계약년월','계약일','보증금(만원)'])
df_final

,주소,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),층,건축년도,도로명,...,latitude,longitude,company,home_cnt,home_size,room_cnt,bath_cnt,bigo,zibun,new_zibun
0,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201501,13,"40,000",5,1988.0,언주로 103,...,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,None,None
2,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201503,2,"50,000",2,1988.0,언주로 103,...,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,None,None
4,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201505,23,"50,000",6,1988.0,언주로 103,...,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,None,None
6,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201506,8,"49,000",3,1988.0,언주로 103,...,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,None,None
8,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201507,22,"50,000",9,1988.0,언주로 103,...,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
578950,서울특별시 중랑구 망우동 508-27,다성,전세,68.40,202203,15,"25,000",4,2004.0,상봉로28길 29-5,...,37.596237,127.094625,(주)준일건설,8,68.40,3,2,None,None,None
578951,서울특별시 중랑구 면목동 1542,면목루브루,전세,55.35,202202,26,"40,000",2,2021.0,겸재로10길 44,...,37.584321,127.078065,주식회사성호건설,42,55.35,3,2,None,None,None
578952,서울특별시 중랑구 면목동 1542,면목루브루,전세,51.85,202204,16,"40,000",2,2021.0,겸재로10길 44,...,37.584321,127.078065,주식회사성호건설,42,51.85,3,2,None,None,None
578953,서울특별시 중랑구 상봉동 106,상봉힐스테이,전세,16.94,202203,9,"28,000",12,2021.0,봉우재로37길 17,...,37.593614,127.087722,(주)엘제이종합건설,55,16.94,1,1,None,None,None
578954,서울특별시 중랑구 상봉동 85-1,솔렌시아3(85-1),전세,42.27,202202,28,"28,000",7,2018.0,봉우재로49길 9,...,37.594199,127.092067,-,35,42.27,3,2,None,중랑구 상봉동 85-1,중랑구 상봉동 85-1

In [10]:
df_final.to_csv("./전세_실거래_데이터_완성본.csv", encoding='cp949')