In [2]:
import pandas as pd
df_edu=pd.read_csv('edu.csv')
df_bus_station = pd.read_csv('bus_station.csv')
df_station_distance = pd.read_csv('station_distance.csv')
df_station_info=pd.read_csv('station_info.csv')
df = pd.read_csv('df_final_include_gu.csv')

C:\Users\seokchan\AppData\Local\Temp/ipykernel_30752/2538145795.py:6: DtypeWarning: Columns (24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('df_final_include_gu.csv')

In [3]:
df

,Unnamed: 0,주소,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),층,건축년도,...,latitude,longitude,company,home_cnt,home_size,room_cnt,bath_cnt,bigo,zibun,new_zibun
0,0,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201501,13,"40,000",5,1988.0,...,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,None,None
1,1,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201501,13,"40,000",5,1988.0,...,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,강남구 개포동 655-2,강남구 개포동 655-2
2,2,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201503,2,"50,000",2,1988.0,...,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,None,None
3,3,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201503,2,"50,000",2,1988.0,...,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,강남구 개포동 655-2,강남구 개포동 655-2
4,4,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201505,23,"50,000",6,1988.0,...,37.481215,127.052733,현대산업개발(주),54,77.75,3,1,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579245,579245,서울특별시 중랑구 망우동 508-27,다성,전세,68.40,202203,15,"25,000",4,2004.0,...,37.596237,127.094625,(주)준일건설,8,68.40,3,2,None,None,None
579246,579246,서울특별시 중랑구 면목동 1542,면목루브루,전세,55.35,202202,26,"40,000",2,2021.0,...,37.584321,127.078065,주식회사성호건설,42,55.35,3,2,None,None,None
579247,579247,서울특별시 중랑구 면목동 1542,면목루브루,전세,51.85,202204,16,"40,000",2,2021.0,...,37.584321,127.078065,주식회사성호건설,42,51.85,3,2,None,None,None
579248,579248,서울특별시 중랑구 상봉동 106,상봉힐스테이,전세,16.94,202203,9,"28,000",12,2021.0,...,37.593614,127.087722,(주)엘제이종합건설,55,16.94,1,1,None,None,None
579249,579249,서울특별시 중랑구 상봉동 85-1,솔렌시아3(85-1),전세,42.27,202202,28,"28,000",7,2018.0,...,37.594199,127.092067,-,35,42.27,3,2,None,중랑구 상봉동 85-1,중랑구 상봉동 85-1

In [4]:
df_edu

        edu
0         1
1         1
2         1
3         1
4         1
...     ...
579245    0
579246    0
579247    0
579248    0
579249    0

[579250 rows x 1 columns]

In [10]:
df = pd.merge(df,df_edu,left_index=True,right_index=True)

In [12]:
df=df[df['bath_cnt']!='-']

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 578955 entries, 0 to 579249
Data columns (total 30 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  578955 non-null  int64
 1   주소          578955 non-null  object
 2   단지명         578955 non-null  object
 3   전월세구분       578955 non-null  object
 4   전용면적(㎡)     578955 non-null  float64
 5   계약년월        578955 non-null  int64
 6   계약일         578955 non-null  int64
 7   보증금(만원)     578955 non-null  object
 8   층           578955 non-null  int64
 9   건축년도        578955 non-null  float64
 10  도로명         578955 non-null  object
 11  동_단지        578955 non-null  object
 12  시군구         578955 non-null  object
 13  번지          578955 non-null  object
 14  구           578955 non-null  object
 15  apt         578955 non-null  object
 16  road        578955 non-null  object
 17  new_apt     578955 non-null  object
 18  new_road    578955 non-null  object
 19  latitude    578955 non-null  float64
 20  longitude   578955 non-null  float64
 21  company     578955 non-null  object
 22  home_cnt    578955 non-null  int64
 23  home_size   578955 non-null  float64
 24  room_cnt    578955 non-null  object
 25  bath_cnt    578955 non-null  object
 26  bigo        578955 non-null  object
 27  zibun       578955 non-null  object
 28  new_zibun   578955 non-null  object
 29  edu         578955 non-null  int64
dtypes: float64(5), int64(6), object(19)
memory usage: 136.9+ MB

In [16]:
df = pd.merge(df,df_bus_station,left_index=True,right_index=True)

In [17]:
df = pd.merge(df,df_station_distance,left_index=True,right_index=True)

In [18]:
df = pd.merge(df,df_station_info,left_index=True,right_index=True)

In [19]:
df

,Unnamed: 0,주소,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),층,건축년도,...,sub_dist,1호선,2호선,3호선,4호선,5호선,6호선,7호선,8호선,9호선
0,0,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201501,13,"40,000",5,1988.0,...,0.84,0,0,1,0,0,0,0,0,0
1,1,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201501,13,"40,000",5,1988.0,...,0.84,0,0,1,0,0,0,0,0,0
2,2,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201503,2,"50,000",2,1988.0,...,0.84,0,0,1,0,0,0,0,0,0
3,3,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201503,2,"50,000",2,1988.0,...,0.84,0,0,1,0,0,0,0,0,0
4,4,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201505,23,"50,000",6,1988.0,...,0.84,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
578950,578950,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202109,18,"33,500",8,2021.0,...,0.81,0,0,0,0,0,0,1,0,0
578951,578951,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202110,29,"33,500",8,2021.0,...,0.95,0,0,0,0,0,0,1,0,0
578952,578952,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202110,29,"33,500",8,2021.0,...,0.95,0,0,0,0,0,0,1,0,0
578953,578953,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202201,2,"33,200",5,2021.0,...,0.40,0,0,0,0,0,0,1,0,0
578954,578954,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202201,2,"33,200",5,2021.0,...,0.65,0,0,0,0,0,0,1,0,0

In [20]:
df = df.drop('Unnamed: 0',axis=1)

In [21]:
df

,주소,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),층,건축년도,도로명,...,sub_dist,1호선,2호선,3호선,4호선,5호선,6호선,7호선,8호선,9호선
0,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201501,13,"40,000",5,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
1,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201501,13,"40,000",5,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
2,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201503,2,"50,000",2,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
3,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201503,2,"50,000",2,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
4,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201505,23,"50,000",6,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
578950,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202109,18,"33,500",8,2021.0,서오릉로 80-1,...,0.81,0,0,0,0,0,0,1,0,0
578951,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202110,29,"33,500",8,2021.0,서오릉로 80-1,...,0.95,0,0,0,0,0,0,1,0,0
578952,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202110,29,"33,500",8,2021.0,서오릉로 80-1,...,0.95,0,0,0,0,0,0,1,0,0
578953,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202201,2,"33,200",5,2021.0,서오릉로 80-1,...,0.40,0,0,0,0,0,0,1,0,0
578954,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202201,2,"33,200",5,2021.0,서오릉로 80-1,...,0.65,0,0,0,0,0,0,1,0,0

In [28]:
df = df.drop_duplicates(['주소','전용면적(㎡)','계약년월','계약일','보증금(만원)'])

In [29]:
df.to_csv('df_add_subwayedu.csv')

In [30]:
df

,주소,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),층,건축년도,도로명,...,sub_dist,1호선,2호선,3호선,4호선,5호선,6호선,7호선,8호선,9호선
0,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201501,13,"40,000",5,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
2,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201503,2,"50,000",2,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
4,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201505,23,"50,000",6,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
6,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201506,8,"49,000",3,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
8,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),전세,77.75,201507,22,"50,000",9,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
578945,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202108,2,"33,500",10,2021.0,서오릉로 80-1,...,0.47,1,0,0,1,0,1,0,0,0
578947,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202108,20,"33,500",8,2021.0,서오릉로 80-1,...,3.56,0,0,1,1,0,1,0,0,0
578949,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202109,18,"33,500",8,2021.0,서오릉로 80-1,...,0.33,0,0,1,0,0,1,0,0,0
578951,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202110,29,"33,500",8,2021.0,서오릉로 80-1,...,0.95,0,0,0,0,0,0,1,0,0
578953,서울특별시 은평구 대조동 179-16,북한산포레스트,전세,29.02,202201,2,"33,200",5,2021.0,서오릉로 80-1,...,0.40,0,0,0,0,0,0,1,0,0

In [32]:
df=df[['주소','단지명','전용면적(㎡)','계약년월','계약일','보증금(만원)','층','건축년도','도로명','latitude','longitude','home_cnt','home_size','room_cnt','bath_cnt','edu','bus','sub_dist','1호선','2호선','3호선','4호선','5호선','6호선','7호선','8호선','9호선']]

In [49]:
df.to_csv('bussubedu1.csv',index=False)

In [48]:
df.reset_index()

,index,주소,단지명,전용면적(㎡),계약년월,계약일,보증금(만원),층,건축년도,도로명,...,sub_dist,1호선,2호선,3호선,4호선,5호선,6호선,7호선,8호선,9호선
0,0,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),77.75,201501,13,"40,000",5,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
1,2,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),77.75,201503,2,"50,000",2,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
2,4,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),77.75,201505,23,"50,000",6,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
3,6,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),77.75,201506,8,"49,000",3,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
4,8,서울특별시 강남구 개포동 655-2,개포2차현대아파트(220),77.75,201507,22,"50,000",9,1988.0,언주로 103,...,0.84,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521277,578945,서울특별시 은평구 대조동 179-16,북한산포레스트,29.02,202108,2,"33,500",10,2021.0,서오릉로 80-1,...,0.47,1,0,0,1,0,1,0,0,0
521278,578947,서울특별시 은평구 대조동 179-16,북한산포레스트,29.02,202108,20,"33,500",8,2021.0,서오릉로 80-1,...,3.56,0,0,1,1,0,1,0,0,0
521279,578949,서울특별시 은평구 대조동 179-16,북한산포레스트,29.02,202109,18,"33,500",8,2021.0,서오릉로 80-1,...,0.33,0,0,1,0,0,1,0,0,0
521280,578951,서울특별시 은평구 대조동 179-16,북한산포레스트,29.02,202110,29,"33,500",8,2021.0,서오릉로 80-1,...,0.95,0,0,0,0,0,0,1,0,0
521281,578953,서울특별시 은평구 대조동 179-16,북한산포레스트,29.02,202201,2,"33,200",5,2021.0,서오릉로 80-1,...,0.40,0,0,0,0,0,0,1,0,0